- name: Basic Server Setup
  hosts: local
  become: false  # Optional: if your tasks need root access
  tasks:
    - name: Example task
      debug:
        msg: "Hello, this is a basic setup"
    - name: Copy the artifact to the deployment directory
      copy:
        src: "{{ lookup('env','WORKSPACE') }}/target/MavenApp-1.0-SNAPSHOT.jar"
        dest: "/opt/deployment/MavenApp.jar"
